name: Build MinecraftBedrockArchive Variants

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        target: [arm64-v8a]
        variant: 
          - name: default
            path_type: default
            folder: default
          - name: path-mod
            path_type: path-mod
            folder: path-mod
            
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26b
        
    - name: Setup Xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        
    - name: Configure and Build
      run: |
        xmake f -p android --ndk=${{ steps.setup-ndk.outputs.ndk-path }} -a ${{ matrix.target }} -m release --path_type=${{ matrix.variant.path_type }} -c --yes
        xmake
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MinecraftBedrockArchive-${{ matrix.target }}-${{ matrix.variant.folder }}
        path: build/target/${{ matrix.variant.path_type }}/libMinecraftBedrockArchive.so
