name: Build MinecraftBedrockArchive Variants

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26b
        
    - name: Setup Xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        
    - name: Configure and Build (default)
      run: |
        xmake f -p android --ndk=${{ steps.setup-ndk.outputs.ndk-path }} -a arm64-v8a -m release --path_type=default -c --yes
        xmake
        
        mkdir -p archive_folder/default
        cp build/android/arm64-v8a/release/libMinecraftBedrockArchive.so archive_folder/default/libMinecraftBedrockArchive.so

    - name: Configure and Build (path-mod)
      run: |
        xmake f -p android --ndk=${{ steps.setup-ndk.outputs.ndk-path }} -a arm64-v8a -m release --path_type=path-mod -c --yes
        xmake
        
        mkdir -p archive_folder/path-mod
        cp build/android/arm64-v8a/release/libMinecraftBedrockArchive.so archive_folder/path-mod/libMinecraftBedrockArchive.so

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MinecraftBedrockArchive
        path: archive_folder/
